name: Run Unit Tests & Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        id: test
        continue-on-error: false  # Stop if tests fail
        run: |
          source venv/bin/activate
          python -m unittest discover tests

      - name: Send Discord Notification
        if: always()  # Always run this step (pass or fail)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ Tests Passed!"
            COLOR=3066993  # Green
          else
            STATUS="❌ Tests Failed!"
            COLOR=15158332  # Red
          fi

          curl -H "Content-Type: application/json" -X POST -d "{
            \"embeds\": [{
              \"title\": \"$STATUS\",
              \"description\": \"Unit tests for the latest commit have completed.\",
              \"color\": $COLOR
            }]
          }" $DISCORD_WEBHOOK_URL
